name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          sudo chmod +x /usr/local/bin/composer

      - name: Debug Environment
        run: |
          echo "Current PATH: $PATH"
          php -v
          composer -V || echo "Composer not found"

      - name: Deploy to server
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST bash -c '
            source ~/.bashrc || true &&
            source ~/.profile || true &&
            cd ~/public_html/knowledge-hub &&
            git pull origin main &&
            /usr/local/bin/composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            composer dump-autoload &&
            php artisan view:clear &&
            php artisan route:clear &&
            php artisan config:clear
          '
